export const PROJECTSLOADING = "PROJECTSLOADING";
export const PROJECTSLOADED = "PROJECTSLOADED";
export const CONTACTSUBMITLOADER = "CONTACTSUBMITLOADER";
export const CONTACTSUBMITMESSAGE = "CONTACTSUBMITMESSAGE";
